### ISSUE TITLE
Ensure merging of definitions with AECD

### ISSUE THREAD

**Issue by fbanados** [UAlbertaALTLab/crk-db#116]
There is an expected behaviour that definitions with AECD will be merged. Like:
![image](https://github.com/UAlbertaALTLab/crk-db/assets/248151/c3d41a5f-b730-4a84-a9d7-daff2715952b)
This could fail when similarity metrics are not precise enough, or where senses include other content.  e.g., 
![image](https://github.com/UAlbertaALTLab/crk-db/assets/248151/c5b27720-60c0-4006-b786-c1548355848d)

**Comment by fbanados** [comment]
With the new FSTs, the following AECD definition should be merged:
![Screenshot 2024-06-18 at 5 07 47 PM](https://github.com/UAlbertaALTLab/crk-db/assets/248151/34b1b614-dfde-4c5c-bfb6-461d08962c8c)

**Comment by fbanados** [comment]
FOMA should be able to deal with the example case.  Confirm that is currently happening.

A separate issue is the merging of entries that are alike but not the same, which currently should not happen.

**Comment by aarppe** [comment]
FOMA behavior demo, which shows that the capitalized _S/he_ should get properly converted:

```
foma -l src/fst/transcriptions/transcriptor-cw-eng-verb-entry2inflected-phrase-w-flags-and-templates.xfscript

foma[1]: down Prs+1Sg+s/he sleeps
I sleep

foma[1]: down Prs+1Sg+S/he sleeps
I sleep
```

**Comment by fbanados** [comment]
The issues have been addresssed:

![Screenshot 2024-07-24 at 5 28 33 PM](https://github.com/user-attachments/assets/73eec83b-dbd6-4dd6-b003-d920c40c9c99)
![Screenshot 2024-07-24 at 5 30 12 PM](https://github.com/user-attachments/assets/a48c79f5-d70a-49dc-87e5-60c0a0c841c6)
