### ISSUE TITLE
possessive/non-possessive stems should be presented in linguistInfo HTML tag

### ISSUE THREAD

**Issue by fbanados** [UAlbertaALTLab/crk-db#117]
e.g. atimw- and -têm- in the field, not just atimw-
![Screenshot 2024-06-25 at 4 14 58 PM](https://github.com/UAlbertaALTLab/morphodict/assets/248151/f2b392da-a244-42c4-af5a-ad3793c5ea59)

for example,

```
<table colspan=2>
<tr><td>Nonposs</td><td>atimw-</td></tr>
<tr><td>Poss</td><td>-têm-</td></tr>
</table>
```

**Comment by fbanados** [comment]
With commit bfa1362, after importing the new importjson, itwewina generates tables like the following: ![Screenshot 2024-06-26 at 5 51 55 PM](https://github.com/UAlbertaALTLab/crk-db/assets/248151/4f79860c-b5e2-41f4-b3d0-fe7f8522eca0)

**Comment by aarppe** [comment]
Looks good. We might adjust the table a bit, adding headers:

```
<table colspan=2>
<tr><td></td><td>Stem</td></tr>
<tr><td>Nonposs</td><td>atimw-</td></tr>
<tr><td>Poss</td><td>-têm-</td></tr>
</table>
```
I'd need to add the appropriate terms to `crk.altlabel.tsv` for `Stem`, perhaps the same as the linguistic and plain English labels, and [ocêpihk](https://itwewina.altlab.app/word/oc%C3%AApihk/) in Cree.

**Comment by fbanados** [comment]
New importjson and code deployment in https://itwewina.altlab.dev/ should have a current version that works for this code.  Issue should be ready for closing.

**Comment by fbanados** [comment]
This has been implemented as follows: ![Screenshot 2024-07-24 at 5 26 36 PM](https://github.com/user-attachments/assets/49d5cb12-efa8-4248-93cb-20ba4ba5ec5e)

Ready to go up, as discussed last week, this issue can be closed.

**Comment by aarppe** [comment]
Related to this, added relabelings for `Stem` and `Alt` in https://github.com/UAlbertaALTLab/morphodict/commit/74d911ba41aa1301146412340f62b2b1efe15a9e
