### ISSUE TITLE
acimosis as a formOf only, or as a separate entry

### ISSUE THREAD

**Issue by fbanados** [UAlbertaALTLab/crk-db#130]
Acimosis currently has its own entry, separate from the inflection of `atim`:

![Screenshot 2024-07-25 at 5 34 57 PM](https://github.com/user-attachments/assets/abb17c8b-b836-4bb7-90fb-600fdc78b5fe)

Maybe it should only appear as an inflection of `atim`?  The tradeoff is that the paradigm for `atim` currently only shows the Singular Diminutive (`acimosis`), while the paradigm for `acimosis` shows Singular, Plural (`acimosisak`), Obviative (`acimosisa`), plus many possession inflections (like `nicacimosisim`).

I am not sure whether this is even worth pursuing.  But if it is, it would require the following changes:

- FST: Currently it provides two analysis:
```
acimosis	acimosis+N+A+Sg
acimosis	atim+N+A+Der/Dim+N+A+Sg
```
- Updated analysis in `AECD_crk2eng_ALTLab`, currently `acimosis+N+A+Sg`.   Also, we should have a system to re-run the FST analyses on the more stable dictionaries.

These are useful but minor things.  I'm writing this issue to document it, but I believe the current version of the `importjson` to be good enough to move on to other work.  

On a separate note I will try again to put up `itwewina.dev` tomorrow with the new version of the dictionary, but even if that doesn't work, and if there are no requests for urgent changes, I can upgrade the `altlab` repo version (and the production database) with the new importjson that should have most if not all of the `MD` and `AECD` entries.

**Comment by aarppe** [comment]
I think we have ended up considering diminutivization similar to preverbs, i.e. a derivational process rather than inflection, and thus keeping the entries separate. I noticed somewhere that we might be generating English translations corresponding to the diminutive forms, but while the English FOMA FSTs allow for it, I think we abandoned that approach.
