### ISSUE TITLE
create FST LEXC files from database

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/crk-db#14]
Create the FST LEXC files from the ALTLab database.

The current scripts that convert the TSV version of CW to LEXC lives in the [lang-crk](https://github.com/giellalt/lang-crk) repo.

* https://github.com/giellalt/lang-crk/blob/develop/tools/shellscripts/wolvengrey-toolbox2fst-tsv.sh
   - adds (tentative) FST stems and prepares it for conversion to LEXC
* https://github.com/giellalt/lang-crk/blob/develop/tools/shellscripts/wolvengrey-new2lexc.sh
   - converts CW TSV to LEXC

**Comment by fbanados** [comment]
Generating the lexc files will remain at the lang-crk repo for the time being, with code in the private altlab/ repo.
