### ISSUE TITLE
create a user interface for modifying dictionary content

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/crk-db#2]
More properly on the longer term, aggregating Cree Words and the Maskwacîs Dictionary should be fixed by creating a proper lexical database of the Maskwacîs Dictionary content, which includes the following information:

1. Original MD dictionary entry.
2. Normatized MD dictionary entry.
3. Matching CW dictionary entry, if any. May require the creation of a unique ID on CW side, if match is ambiguous.
4. CW-MD English gloss comparison classification (reflecting how the English glosses are presented if comparable).
5. Cree stem (when appropriate, not for multiword phrases) <- can be extracted from CW, if match established, but likely good to specify under MD dictionary entry as well.
6. POS and inflectional class (following CW style).
7. Rapid Words semantic classification numbers
8. Rapid Words semantic classification labels
9. POS-parsed version of MD English gloss (useful for Eng-to-Cree search and in creating inflected English paradigm cells, if not already in CW).

The above information, coupled with comparably organized CW content, will allow for the instantaneous and easy dynamic creation of the aggregated Cree dictionaries' content.

Eventually, this will be extended as a result of the validation of the new words and sentences from the Spoken Dictionary of Maskwacîs Cree project.

We should consider whether this should be part of the validation project (as it serves it) or a separate small project.

_Originally posted by @aarppe in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/165#issuecomment-574026020_

**Comment by dwhieb** [comment]
Closing since this is now outside the scope of this single repo (but still very much on my radar).
