### ISSUE TITLE
incorporate semantic classifications of CW

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/crk-db#25]
Incorporate Daniel Dacanay's semantic classifications of CW words into the ALTLab database.

These files should already live in the ALTLab repo (add them if not).

This could even be its own independent dictionary database; however, Arok would probably like this information in his Toolbox file as well.

**Comment by fbanados** [comment]
Wordnet and RapidWords classifications from sources are currently being incorporated into importjson.
