### ISSUE TITLE
add FST stems

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/crk-db#35]
Add an `fstStem` field for any entries that require it. This information can be acquired from the TSV version of the Toolbox database, and should be stored permanently in the main entries of the database. There are somewhere in the range of ~1,500 entries total where this information has been added. This data should be retrieved and added to the main entry in the dictionary database. Forms marked as "CHECK" are ones that need FST stems.

**Comment by aarppe** [comment]
@dwhieb The specs are the following:
* an empty cell means we can use the `\stm` field as the **fststem**.
* a cell with a form with a preceding or following hyphen means that is the **fststem** to be used.
* Forms marked as CHECK require manual scrutiny.
