### ISSUE TITLE
clean up the MD database

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/crk-db#65]
First create an ALTLab version of the MD database and archive the original version.

- [x] extract examples + example translations into their own fields
- [x] extract cross-references into their own field
- [x] consistently represent separate senses with `1.`, `2.`, etc.
- [x] extract parentheticals into their own field (so that there's just one sentence per definition)
- [x] ~~update mappings~~

Will require an initial planning meeting to finalize the details of each task.

**Comment by DBDacanay** [comment]
16/5/21 Wordsenses have been separated and numbered for the full database., and all cross-references in entries (excluding those in example sentences) have been logged in a new column

**Comment by DBDacanay** [comment]
19/5/21 Parentheticals and example words have been extracted from the English glosses and added to two separate columns. Some parentheticals, namely those either highly useful or overtly necessary to understand the full meaning of the Cree word, were retained in the gloss in addition to being added to the parenthetical column.

**Comment by dwhieb** [comment]
Good call on duplicating the parenthetical in some instances!
